# Generated by Django 3.0.3 on 2020-02-18 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecream',
            name='available',
            field=models.CharField(choices=[('da', 'daily'), ('we', 'weekly'), ('se', 'seasonal')], default='daily', max_length=20),
        ),
        migrations.AddField(
            model_name='icecream',
            name='base',
            field=models.CharField(choices=[('choc', 'chocolate'), ('van', 'vanilla')], default='vanilla', max_length=20),
        ),
        migrations.AddField(
            model_name='icecream',
            name='date_churned',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
